name: cuba_weather_dart
description: Application programming interface of the Cuba Weather project implemented in Dart
version: 3.0.3
homepage: https://github.com/cuba-weather/cuba-weather-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  xml: ^3.7.0
  html: ^0.14.0+3
