name: cuba_weather_dart
description: Application programming interface of the Cuba Weather project implemented in Dart
version: 3.1.1
homepage: https://github.com/cuba-weather/cuba-weather-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  xml: ^3.7.0
  html: ^0.14.0+3
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.8.0
  json_serializable: ^3.2.5
