name: cuba_weather_dart
description: Application programming interface of the Cuba Weather project implemented in Dart
version: 2.4.0
homepage: https://github.com/cuba-weather/cuba-weather-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cuba_weather_insmet_dart: ^0.2.1
  cuba_weather_redcuba_dart: ^2.3.0
